[program:fhu]
command=/home/lcas/fhu_auto/venv/bin/python /home/lcas/fhu_auto/app.py
autostart=true
autorestart=true
startsecs=5
startretries=3
directory=/home/lcas/fhu_auto
user=lcas
environment=PORT="5000"
stopsignal=int
stopwaitsecs=10
stopasgroup=true
killasgroup=true